anngeno_file: PATH_TO_FILE
# anngeno_file: PATH_TO_FILE
# associations_df_path: PATH_TO_FILE
associations_df_path: PATH_TO_FILE
prs_pheno_map_file: PATH_TO_FILE
prs_file: PATH_TO_FILE
maf_upper_bound: 0.001

# annotation_file: PATH_TO_FILE
phenotypes_for_testing:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol
  - Red_blood_cell_erythrocyte_count
  - HDL_cholesterol
  - IGF_1
  - LDL_direct
  - Lymphocyte_percentage
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Mean_platelet_thrombocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - SHBG
  - Standing_height
  - Triglycerides
  - Urate
  - Total_bilirubin
  - Body_mass_index_BMI
  - Glucose
  - Vitamin_D
  - Albumin
  - Total_protein
  - Cystatin_C
  - Gamma_glutamyltransferase
  - Alkaline_phosphatase
  - Creatinine
  - Whole_body_fat_free_mass
  - Forced_expiratory_volume_in_1_second_FEV1
  - Glycated_haemoglobin_HbA1c

covariates: 
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20

rare_variant_annotations:
  baselines:
  - loftee_hc
  - am_pathogenicity
  splicing:
  - AbSplice2_max
  - loss_score