rare_variant_annotations:
  # plof:
  #   loftee_hc:
  #     color: "#DD4344"
  #     label: "LOFTEE HC"
      
  missense:
    am_pathogenicity: 
      color: "#FFD700"  # Pure Gold Yellow
      label: "AlphaMissense"
    esmscoremissense: 
      color: "#FFA500"  # Pure Orange
      label: "ESM1v"
      direction: -1
    esm1b_llr:
      color: "#FF6600"  # Vivid Orange-Red
      label: "ESM1b"
      direction: -1
    cpt1_llr:
      color: "#E63000"  # Strong Red-Orange
      label: "CPT-1"
    revel_score:
      color: "darkred"  # Deep Pure Red
      label: "REVEL"
    # score_pai3d: 
    #   color: "#FFEC80"  # Pale Yellow (lighter end)
    #   label: "PrimateAI-3D"

  genetic_diversity:
    cadd_raw:
      color: "#1f77b4"
      label: "CADD Raw"

  conservation:
    # gpn_star_llr_calibrated_mean: 
    #   color: "#942c80"
    #   label: "GPN-Star"
    #   direction: -1
    gpn_score: 
      color: "pink"
      label: "GPN-MSA"
      direction: -1
    verphylop: 
      color: "#483D8B"  # Dark Slate Blue
      label: "Vertebrate PhyloP"

  splicing:
    delta_score:
      color: "#8BC34A"  # Light Green
      label: "SpliceAI"
    pangolin_score:
      color: "#2E7D32"  # Forest Green
      label: "Pangolin"
    absplice_dna_max:
      color: "#26C6DA"  # Bright Turquoise / Cyan
      label: "AbSplice (max)"
    absplice2_max:
      color: "#00838F"  # Deep Cyan
      label: "AbSplice2 (max)"
  
  regulatory_nondir:
    promoterai_abs:
      color: "#80CBC4"  # Pale Teal (Low/Min)
      label: "PromoterAI abs"
    abexp_abs_max:
      color: "#b5de2b"
      label: "AbExp abs max"
  
  3utr:
    aparent2:
      color: "#FFA500"  # Orange (uSTOP Gained)
      label: "Aparent 2"
      # direction: -1

  # naive:
  #   relative_cds_position:
  #     color: "#b5de2b"
  #     label: "Relative CDS\nPosition"
  #     direction: -1

  regulatory:
    promoterai:
      color: "#00A99D"
      label: "PromoterAI"
      direction: -1
    promoterai_under:
      color: "#00A99D"
      label: "PromoterAI"
      direction: -1
    promoterai_over:
      color: "#00A99D"
      label: "PromoterAI"
      # direction: -1
    abexp_min:
      color: "#b5de2b"
      label: "AbExp min"
      direction: -1
    abexp_max:
      color: "#b5de2b"
      label: "AbExp max"
      # direction: -1
    fz_all_mean:
      color: "#1f77b4"
      label: "Flashzoi mean\nacross RNA (all)"
    fz_blood_min:
      color: "crimson"
      label: "Flashzoi min\nacross RNA (blood)"
      direction: -1
    fz_all_min:
      color: "#FFA500"  # Orange (uSTOP Gained)
      label: "Flashzoi min\nacross RNA (all)"
      direction: -1
    fz_blood_max:
      color: "crimson"
      label: "Flashzoi max\nacross RNA (blood)"
    fz_all_max:
      color: "#FFA500"  # Orange (uSTOP Gained)
      label: "Flashzoi max\nacross RNA (all)"