maf: 0.001

covariates:
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20

rare_variant_annotations:
  exp_assays:
    scaled_fitness:
      color: "#66BB6A"  # Light Green
      label: 'aPCA fitness'
    DMS:
      color: "#66BB6A"  # Light Green
      label: 'DMS'
      direction: -1
    DMS_score_combined:
      color: "#4DB6AC"  # Teal/Mint
      label: 'DMS (combined)'
      direction: -1
    LDL_uptake_functional:
      color: "#66BB6A"  # Light Green
      label: 'LDL uptake functional'
      direction: -1
    LDLR_cell_surface_abundance:
      color: "#81C784"  # Lighter Green
      label: 'LDLR cell surface abundance'
      direction: -1

  missense:
    # YELLOWS - ClinVar-based tools (curated databases)
    clinpred_score:
      color: "#FFDC80"  # Pale Yellow (lighter end)
      # color: "#FFFF00"  # Pure Bright Yellow
      label: "ClinPred"
    bayes_del:
      color: "#FFBF00"  # Gold Yellow
      label: "BayesDel"
    polyphen:
      color: "#FF90AA"  # Pink
      label: "PolyPhen2"
    revel_score:
      color: "#FF7000"  # Dark Orange
      label: "REVEL"
    
    # BROWN/REDS - Curation-free tools (AI/evolutionary models)
    am_pathogenicity:
      color: "#E63946"  # Crimson Red
      label: "AlphaMissense"
    cpt1_llr:
      color: "#AF0000"  # Dark Red
      label: "CPT-1"
    esmscoremissense:
      color: "#CD853F"  # Peru Brown 
      label: "ESM1v"
      direction: -1
    # esm1b_llr:
    #   color: "#8B4513"  # Saddle Brown
    #   label: "ESM1b"
    #   direction: -1

  genetic_diversity:
    cadd_raw:
      color: "chocolate"
      label: "CADD Raw"

  conservation:
    gpn_score: 
        color: "#807DBA"  # Vibrant Magenta/Pink-Purple
        label: "GPN-MSA"
        direction: -1
    # Vertebrates - Blues
    verphylop: 
      color: "#08306B"  # Darkest Blue
      label: "Vertebrate PhyloP"
    # zooverphylop:
    #   color: "#2879B9"  # Medium Blue
    #   label: "Zoonomia Vertebrate PhyloP"
    
    # Mammals - Teals/Cyans
    mamphylop: 
      color: "#006B6B"  # Teal
      label: "Mammalian PhyloP"
    
    # Primates - Purples
    priphylop:
      color: "#3F007D"  # Darkest Purple
      label: "Primate PhyloP"
    # zoopriphylop:
    #   color: "#807DBA"  # Medium-Light Purple
    #   label: "Zoonomia Primate PhyloP"

  naive:
    relative_cds_position:
      color: "#b5de2b"
      label: "Relative CDS\nPosition"
      direction: -1

  plof:
    loftee_hc:
      color: "#E31A1C" # Dark Red
      label: "LOFTEE HC"

  protein_domains:
    mobi_curated_disorder_priority:
      color: "#E31A1C"  # Dark Red
      label: "Disordered Domain"
    mobi_lip_full:
      color: "#1E90FF"  # Dodger Blue
      label: "Linear Interacting Peptides"
    ted_domain:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    low_complexity_domain:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low Complexity Domain"
  
  loftee_protein_domains:
    loftee_disorder:
      color: "#E31A1C"  # Dark Red
      label: "Disordered Domain"
    loftee_lip:
      color: "#1E90FF"  # Dodger Blue
      label: "Linear Interacting Peptides"
    loftee_ted:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    loftee_low_complexity:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low Complexity Domain"