rare_variant_annotations:
  plof:
    loftee_hc:
      color: "#E31A1C" # Dark Red
      label: "LOFTEE HC"
      # direction: -1

  genetic_diversity:
    cadd_raw:
      color: "#1f77b4"
      label: "CADD Raw"
      # direction: -1

  missense:
    am_pathogenicity: 
      color: "#feb72d"
      label: "AlphaMissense"
    esmscoremissense: 
      color: "#feb72d"
      label: "ESM1v"
      # direction: -1
    esm1b_llr:
      color: "#feb72d"
      label: "ESM1b"
      # direction: -1
    cpt1_llr:
      color: "#feb72d"
      label: "CPT-1"
    revel_score:
      color: "#feb72d"
      label: "REVEL"
    polyphen:
      color: "#feb72d"
      label: "PolyPhen2"
    clinpred_score:
      color: "#feb72d"
      label: "ClinPred"
    bayes_del:
      color: "#feb72d"
      label: "BayesDel"
    popeve_score:
      color: "#feb72d"
      label: "popEVE"
      direction: -1
    eve_score:
      color: "#feb72d"
      label: "EVE"
      direction: -1
    pop_adj_eve:
      color: "#feb72d"
      label: "pop-adj-EVE"
      direction: -1
    pop_adj_esm1v:
      color: "#feb72d"
      label: "pop-adj-ESM1v"
      direction: -1
    # score_pai3d: 
    #   color: "#feb72d"
    #   label: "PrimateAI-3D"

  conservation:
    # gpn_star_llr_calibrated_mean: 
    #   color: "#942c80"
    #   label: "GPN-Star"
    #   direction: -1
    gpn_score: 
      color: "#942c80"
      label: "GPN-MSA"
      direction: -1
    verphylop: 
      color: "#942c80"
      label: "Vertebrate PhyloP"
      # direction: -1
    # mamphylop: 
    #   color: "#942c80"
    #   label: "Mammalian PhyloP"
    #   direction: -1
    # zoomamphylop: 
    #   color: "#6a1c81"
    #   label: "Zoonomia mammalian\nPhyloP"
    #   direction: -1
    # zooverphylop: 
    #   color: "#6a1c81"
    #   label: "Zoonomia vertebrate\nPhyloP"
    #   direction: -1

  splicing:
    pangolin_score:
      color: "#28a745"
      label: "Pangolin"
      # direction: -1
    delta_score:
      color: "#28a745"
      label: "SpliceAI"
      # direction: -1
    absplice_dna_max:
      color: "#28a745"
      label: "AbSplice (max)"
      # direction: -1
    absplice2_max:
      color: "#28a745"
      label: "AbSplice2 (max)"
      # direction: -1
  
  regulatory_nondir:
    promoterai_abs:
        color: "#00A99D"
        label: "PromoterAI abs"
        direction: -1
    max_fz_blood:
      color: "pink"
      label: "Flashzoi abs max\nacross blood"
    abexp_min:
        color: "#00A99D"
        label: "AbExp min"
        # direction: -1

  regulatory:
    promoterai:
      color: "#00A99D"
      label: "PromoterAI"
    fz_delta_score:
      color: "salmon"
      label: "Most deviant\nFz score"
    fz_blood:
      color: "crimson"
      label: "Flashzoi Blood"
    abexp_min:
        color: "#00A99D"
        label: "AbExp min"
        # direction: -1
        
    # abexp_whole_blood:
    #   color: "#00A99D"
    #   label: "AbExp whole blood"
    # abexp_max:
    #   color: "#00A99D"
    #   label: "AbExp max"
    # promoterai_under:
    #   color: "#00A99D"
    #   label: "PromoterAI under"
    # promoterai_over:
    #   color: "#00A99D"
    #   label: "PromoterAI over"
    
  # naive:
  #   relative_cds_position:
  #     color: "#b5de2b"
  #     label: "Relative CDS\nPosition"
  #     direction: -1    


