rare_variant_annotations:
  plof:
    loftee_hc:
      color: "#DD4344"
      label: "LOFTEE HC"
      # direction: -1

  genetic_diversity:
    cadd_raw:
      color: "#1f77b4"
      label: "CADD Raw"
      # direction: -1

  missense:
    am_pathogenicity: 
      color: "#FFCA28"  # Amber / Golden Yellow
      label: "AlphaMissense"
    esmscoremissense: 
      color: "#FB8C00"  # Rich Orange
      label: "ESM1v"
      direction: -1
    score_pai3d: 
      color: "#D84315"  # Deep Burnt Orange
      label: "PrimateAI-3D"

  conservation:
    # gpn_star_llr_calibrated_mean: 
    #   color: "#942c80"
    #   label: "GPN-Star"
    gpn_score: 
      color: "pink"
      label: "GPN-MSA"
      direction: -1
    verphylop: 
      color: "#483D8B"
      label: "Vertebrate PhyloP"
      # direction: -1
    # mamphylop: 
    #   color: "#942c80"
    #   label: "Mammalian PhyloP"
    #   direction: -1
    # zoomamphylop: 
    #   color: "#6a1c81"
    #   label: "Zoonomia mammalian\nPhyloP"
    #   direction: -1
    # zooverphylop: 
    #   color: "#6a1c81"
    #   label: "Zoonomia vertebrate\nPhyloP"
    #   direction: -1

  splicing:
    delta_score:
      color: "#00838F"  # Deep Cyan
      label: "SpliceAI"
    pangolin_score:
      color: "#8BC34A"  # Light Green
      label: "Pangolin"
    absplice_dna_max:
      color: "#26C6DA"  # Bright Turquoise / Cyan
      label: "AbSplice (max)"
    absplice2_max:
      color: "#2E7D32"  # Forest Green
      label: "AbSplice2 (max)"

  regulatory:
    promoterai:
      color: "#00A99D"
      label: "PromoterAI"
      direction: -1
    abexp_min:
      color: "#b5de2b"
      label: "AbExp min"
      direction: -1
    abexp_max:
      color: "#b5de2b"
      label: "AbExp max"
      direction: -1
    fz_blood_mean:
      color: "crimson"
      label: "Flashzoi mean\nacross RNA blood"
    fz_all_mean:
      color: "#FFA500"  # Orange (uSTOP Gained)
      label: "Flashzoi mean\nacross RNA all"
    # abexp_min:
    #     color: "#80CBC4"
    #     label: "AbExp min"

  regulatory_nondir:
    promoterai_abs:
      color: "#80CBC4"  # Pale Teal (Low/Min)
      label: "PromoterAI abs"
      direction: -1
    abexp_abs_max:
      color: "#b5de2b"
      label: "AbExp abs max"
      direction: -1
    # max_fz_blood:
    #   color: "pink"
    #   label: "Flashzoi abs max\nacross blood"
    #   direction: -1
    # abexp_whole_blood:
    #   color: "#00A99D"
    #   label: "AbExp whole blood"
    # promoterai_under:
    #   color: "#00A99D"
    #   label: "PromoterAI under"
    # promoterai_over:
    #   color: "#00A99D"
    #   label: "PromoterAI over"
    
  3utr:
    aparent2:
      color: "#b5de2b"
      label: "Aparent 2"
    
  # naive:
  #   relative_cds_position:
  #     color: "#b5de2b"
  #     label: "Relative CDS\nPosition"
  #     direction: -1    


