anngeno_file: /home/dnanexus/data_dir/anngeno_training.ag
# associations_df_path: /s/project/deeprvat/ukb_gym/genebass_assocs_33_phenos.parquet
# prs_pheno_map_file: /s/project/deeprvat/deeprvat_input/prs_pheno_map_clean.csv
# prs_file: /s/project/deeprvat/deeprvat_input/PRS.parquet
maf: 0.001

rare_variant_annotations:
  pos_neg_split_annos:
    - CADD_Aparent2_neg
    - CADD_Aparent2_pos
    - CADD_Dst2Splice_neg
    - CADD_Dst2Splice_pos
    - CADD_EsmScoreMissense_neg
    - CADD_EsmScoreMissense_pos
    - CADD_GerpS_neg
    - CADD_GerpS_pos
    - CADD_MMSp_acceptorIntron_neg
    - CADD_MMSp_acceptorIntron_pos
    - CADD_MMSp_acceptor_neg
    - CADD_MMSp_acceptor_pos
    - CADD_MMSp_donorIntron_neg
    - CADD_MMSp_donorIntron_pos
    - CADD_MMSp_donor_neg
    - CADD_MMSp_donor_pos
    - CADD_MMSp_exon_neg
    - CADD_MMSp_exon_pos
    - CADD_RAW_neg
    - CADD_RAW_pos
    - CADD_RawScore_neg
    - CADD_RawScore_pos
    - CADD_RegSeq0_neg
    - CADD_RegSeq0_pos
    - CADD_RegSeq1_neg
    - CADD_RegSeq1_pos
    - CADD_RegSeq2_neg
    - CADD_RegSeq2_pos
    - CADD_RegSeq3_neg
    - CADD_RegSeq3_pos
    - CADD_RegSeq4_neg
    - CADD_RegSeq4_pos
    - CADD_RegSeq5_neg
    - CADD_RegSeq5_pos
    - CADD_RegSeq6_neg
    - CADD_RegSeq6_pos
    - CADD_RegSeq7_neg
    - CADD_RegSeq7_pos
    - CADD_RemapOverlapCL_neg
    - CADD_RemapOverlapCL_pos
    - CADD_ZooVerPhyloP_neg
    - CADD_ZooVerPhyloP_pos
    - CADD_mamPhyloP_neg
    - CADD_mamPhyloP_pos
    - CADD_motifDist_neg
    - CADD_motifDist_pos
    - CADD_motifEScoreChng_neg
    - CADD_motifEScoreChng_pos
    - CADD_priPhyloP_neg
    - CADD_priPhyloP_pos
    - CADD_verPhyloP_neg
    - CADD_verPhyloP_pos
    - gpn_score_neg
    - gpn_score_pos
    - promoterAI_neg
    - promoterAI_pos
  # cadd_annotations:
  #   - DISTANCE
  #   - PolyPhen
  #   - CADD_RAW
  #   - am_pathogenicity
  #   - SpliceAI_delta_score
  #   - Consequence_3_prime_UTR_variant
  #   - Consequence_5_prime_UTR_variant
  #   - Consequence_NMD_transcript_variant
  #   - Consequence_coding_sequence_variant
  #   - Consequence_downstream_gene_variant
  #   - Consequence_frameshift_variant
  #   - Consequence_inframe_deletion
  #   - Consequence_inframe_insertion
  #   - Consequence_intergenic_variant
  #   - Consequence_intron_variant
  #   - Consequence_missense_variant
  #   - Consequence_non_coding_transcript_exon_variant
  #   - Consequence_non_coding_transcript_variant
  #   - Consequence_protein_altering_variant
  #   - Consequence_splice_acceptor_variant
  #   - Consequence_splice_donor_5th_base_variant
  #   - Consequence_splice_donor_region_variant
  #   - Consequence_splice_donor_variant
  #   - Consequence_splice_polypyrimidine_tract_variant
  #   - Consequence_splice_region_variant
  #   - Consequence_start_lost
  #   - Consequence_start_retained_variant
  #   - Consequence_stop_gained
  #   - Consequence_stop_lost
  #   - Consequence_stop_retained_variant
  #   - Consequence_synonymous_variant
  #   - Consequence_upstream_gene_variant
  #   - loftee_hc
  #   - loftee_lc
  #   - AF_ukb
  #   - AFbeta_ukb
  #   - relative_cds_position
  #   - next_in_frame_relative
  #   - pangolin_score
  #   - delta_score
  #   - AbSplice_DNA_max
  #   - AbSplice2_max
  #   - gpn_score
  #   - five_prime_UTR_variant_consequence_uAUG_gained
  #   - five_prime_UTR_variant_consequence_uAUG_lost
  #   - five_prime_UTR_variant_consequence_uFrameShift
  #   - five_prime_UTR_variant_consequence_uSTOP_gained
  #   - five_prime_UTR_variant_consequence_uSTOP_lost
  #   - variant_length
  #   - promoterAI
  #   - CADD_ConsScore
  #   - CADD_GC
  #   - CADD_CpG
  #   - CADD_motifECount
  #   - CADD_motifEHIPos
  #   - CADD_motifEScoreChng
  #   - CADD_cDNApos
  #   - CADD_relcDNApos
  #   - CADD_CDSpos
  #   - CADD_relCDSpos
  #   - CADD_protPos
  #   - CADD_relProtPos
  #   - CADD_Dst2Splice
  #   - CADD_minDistTSS
  #   - CADD_minDistTSE
  #   - CADD_SIFTval
  #   - CADD_PolyPhenVal
  #   - CADD_priPhCons
  #   - CADD_mamPhCons
  #   - CADD_verPhCons
  #   - CADD_priPhyloP
  #   - CADD_mamPhyloP
  #   - CADD_verPhyloP
  #   - CADD_bStatistic
  #   - CADD_targetScan
  #   - CADD_mirSVR-Score
  #   - CADD_mirSVR-E
  #   - CADD_mirSVR-Aln
  #   - CADD_cHmm_E1
  #   - CADD_cHmm_E2
  #   - CADD_cHmm_E3
  #   - CADD_cHmm_E4
  #   - CADD_cHmm_E5
  #   - CADD_cHmm_E6
  #   - CADD_cHmm_E7
  #   - CADD_cHmm_E8
  #   - CADD_cHmm_E9
  #   - CADD_cHmm_E10
  #   - CADD_cHmm_E11
  #   - CADD_cHmm_E12
  #   - CADD_cHmm_E13
  #   - CADD_cHmm_E14
  #   - CADD_cHmm_E15
  #   - CADD_cHmm_E16
  #   - CADD_cHmm_E17
  #   - CADD_cHmm_E18
  #   - CADD_cHmm_E19
  #   - CADD_cHmm_E20
  #   - CADD_cHmm_E21
  #   - CADD_cHmm_E22
  #   - CADD_cHmm_E23
  #   - CADD_cHmm_E24
  #   - CADD_cHmm_E25
  #   - CADD_GerpRS
  #   - CADD_GerpRSpval
  #   - CADD_GerpN
  #   - CADD_GerpS
  #   - CADD_tOverlapMotifs
  #   - CADD_motifDist
  #   - CADD_EncodeH3K4me1-sum
  #   - CADD_EncodeH3K4me1-max
  #   - CADD_EncodeH3K4me2-sum
  #   - CADD_EncodeH3K4me2-max
  #   - CADD_EncodeH3K4me3-sum
  #   - CADD_EncodeH3K4me3-max
  #   - CADD_EncodeH3K9ac-sum
  #   - CADD_EncodeH3K9ac-max
  #   - CADD_EncodeH3K9me3-sum
  #   - CADD_EncodeH3K9me3-max
  #   - CADD_EncodeH3K27ac-sum
  #   - CADD_EncodeH3K27ac-max
  #   - CADD_EncodeH3K27me3-sum
  #   - CADD_EncodeH3K27me3-max
  #   - CADD_EncodeH3K36me3-sum
  #   - CADD_EncodeH3K36me3-max
  #   - CADD_EncodeH3K79me2-sum
  #   - CADD_EncodeH3K79me2-max
  #   - CADD_EncodeH4K20me1-sum
  #   - CADD_EncodeH4K20me1-max
  #   - CADD_EncodeH2AFZ-sum
  #   - CADD_EncodeH2AFZ-max
  #   - CADD_EncodeDNase-sum
  #   - CADD_EncodeDNase-max
  #   - CADD_EncodetotalRNA-sum
  #   - CADD_EncodetotalRNA-max
  #   - CADD_Grantham
  #   - CADD_SpliceAI-acc-gain
  #   - CADD_SpliceAI-acc-loss
  #   - CADD_SpliceAI-don-gain
  #   - CADD_SpliceAI-don-loss
  #   - CADD_MMSp_acceptorIntron
  #   - CADD_MMSp_acceptor
  #   - CADD_MMSp_exon
  #   - CADD_MMSp_donor
  #   - CADD_MMSp_donorIntron
  #   - CADD_Dist2Mutation
  #   - CADD_Freq100bp
  #   - CADD_Rare100bp
  #   - CADD_Sngl100bp
  #   - CADD_Freq1000bp
  #   - CADD_Rare1000bp
  #   - CADD_Sngl1000bp
  #   - CADD_Freq10000bp
  #   - CADD_Rare10000bp
  #   - CADD_Sngl10000bp
  #   - CADD_dbscSNV-ada_score
  #   - CADD_dbscSNV-rf_score
  #   - CADD_RemapOverlapTF
  #   - CADD_RemapOverlapCL
  #   - CADD_EsmScoreMissense
  #   - CADD_EsmScoreInFrame
  #   - CADD_EsmScoreFrameshift
  #   - CADD_RegSeq0
  #   - CADD_RegSeq1
  #   - CADD_RegSeq2
  #   - CADD_RegSeq3
  #   - CADD_RegSeq4
  #   - CADD_RegSeq5
  #   - CADD_RegSeq6
  #   - CADD_RegSeq7
  #   - CADD_Aparent2
  #   - CADD_ZooPriPhyloP
  #   - CADD_ZooVerPhyloP
  #   - CADD_ZooRoCC
  #   - CADD_ZooUCE
  #   - CADD_Roulette-MR
  #   - CADD_Roulette-AR
  #   - CADD_RawScore
  #   - CADD_PHRED
