anngeno_file: /home/dnanexus/data_dir/dms_coding.ag
maf: 0.001

covariates:
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20


rare_variant_annotations:
  genetic_diversity:
    cadd_raw:
      color: "#1f77b4"
      label: "CADD Raw"

  missense:
    am_pathogenicity: 
      color: "#e76e5b"
      label: "AlphaMissense"
    esmscoremissense: 
      color: "#feb72d"
      label: "ESM1v"
      direction: -1

  conservation:
    gpn_score: 
      color: "#942c80"
      label: "GPN-MSA"
      direction: -1
    zooverphylop: 
      color: "#6a1c81"
      label: "Zoonomia vertebrate\nPhyloP"
    verphylop: 
      color: "#440154"
      label: "Vertebrate PhyloP"

  naive:
    relative_cds_position:
      color: "#b5de2b"
      label: "Relative CDS\nPosition"
      direction: -1

  splicing:
    pangolin_score:
      color: "#20c997"
      label: "Pangolin"
    delta_score:
      color: "#00A99D"
      label: "SpliceAI"
    absplice_dna_max:
      color: "#28a745"
      label: "AbSplice (max)"
    absplice2_max:
      color: "#1E8449"
      label: "AbSplice2 (max)"
  
  regulatory:
    promoterai:
      color: "#00A99D"
      label: "PromoterAI"
    

