anngeno_file: PATH_TO_FILE
# associations_df_path: PATH_TO_FILE
# prs_pheno_map_file: PATH_TO_FILE
# prs_file: PATH_TO_FILE
maf: 0.001

covariates: 
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20

rare_variant_annotations:
  missense:
    - loftee_lc
    - CADD_RAW_neg
    - CADD_RAW_pos
    - dms_score_pos
    - dms_score_neg
    - gpn_score_pos
    - gpn_score_neg
    - Consequence_missense_variant
    - am_pathogenicity
    - PolyPhen
    - CADD_SIFTval
    - CADD_priPhCons
    - CADD_mamPhCons
    - CADD_verPhCons