maf: 0.001

covariates:
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20

rare_variant_annotations:
  plof:
    loftee_hc:
      color: "#E31A1C" # Dark Red
      label: "LOFTEE HC"

  plof_consequences:
    consequence_frameshift_variant:
      color: "#E31A1C"  # Dark Red
      label: "VEP Frameshift"
    consequence_stop_gained:
      color: "#FB9A99"  # Light Red
      label: "VEP Stop Gained"
    consequence_splice_donor_variant:
      color: "#6A1B9A"  # Deep Purple
      label: "VEP Splice Donor"
    consequence_splice_acceptor_variant:
      color: "#AB47BC"  # Lighter Orchid/Purple
      label: "VEP Splice Acceptor"
    # --- Start/Stop Lost Family (Oranges/Gold) ---
    consequence_start_lost:
      color: "#E65100"  # Dark Orange
      label: "VEP Start Lost"
    consequence_stop_lost:
      color: "#FFB300"  # Golden Yellow
      label: "VEP Stop Lost"
    # loftee_hc:
    #   color: "#1E90FF"  # Dodger Blue
    #   label: "LOFTEE HC"
    # loftee_lc:
    #   color: "#C6DBEF" # light blue
    #   label: "LOFTEE LC"
  
  dubious_plof:
    start_stop_lost:
      color: "#C6DBEF" # light blue
      label: "Start/Stop Lost"

  genetic_diversity:
    cadd_raw:
      color: "#1f77b4"
      label: "CADD Raw"

  missense:
    am_pathogenicity: 
      color: "#feb72d"
      label: "AlphaMissense"
    score_pai3d: 
      color: "#feb72d"
      label: "PrimateAI-3D"
    esmscoremissense: 
      color: "#feb72d"
      label: "ESM1v"
      direction: -1

  protein_domains:
    mobi_curated_disorder_priority:
      color: "#E31A1C"  # Dark Red
      label: "Disordered domain"
    mobi_lip_full:
      color: "#1E90FF"  # Dodger Blue
      label: "LIP domain"
    ted_domain:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    low_complexity_domain:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low complexity domain"
  
  loftee_protein_domains:
    loftee_disorder:
      color: "#E31A1C"  # Dark Red
      label: "Disordered domain"
    loftee_lip:
      color: "#1E90FF"  # Dodger Blue
      label: "LIP domain"
    loftee_ted:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    loftee_low_complexity:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low complexity domain"

  conservation:
    gpn_star_llr_calibrated_mean: 
      color: "#942c80"
      label: "GPN-Star"
      direction: -1
    gpn_score: 
      color: "#942c80"
      label: "GPN-MSA"
      direction: -1
    verphylop: 
      color: "#942c80"
      label: "Vertebrate PhyloP"
    # mamphylop: 
    #   color: "#942c80"
    #   label: "Mammalian PhyloP"

  splicing:
    pangolin_score:
      color: "#28a745"
      label: "Pangolin"
    delta_score:
      color: "#28a745"
      label: "SpliceAI"
    absplice_dna_max:
      color: "#28a745"
      label: "AbSplice (max)"
    absplice2_max:
      color: "#28a745"
      label: "AbSplice2 (max)"
  
  regulatory_nondir:
    promoterai_abs:
      color: "#80CBC4"  # Pale Teal (Low/Min)
      label: "PromoterAI abs"
      # direction: -1
    abexp_abs_max:
      color: "#80CBC4"  # Pale Teal (Low/Min)
      label: "AbExp abs max"
    # abexp_min:
    #   color: "#80CBC4"  # Pale Teal (Low/Min)
    #   label: "AbExp min"
    #   direction: -1
  
  regulatory:
    promoterai:
      color: "#00A99D"
      label: "PromoterAI"
    # abexp_whole_blood:
    #   color: "#00A99D"
    #   label: "AbExp whole blood"
    # spliceai_delta_score:
    #   color: "#28a745"
    #   label: "SpliceAI"

  utr_annotator:
    five_prime_utr_variant_consequence_uaug_gained:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Start Gain"
    five_prime_utr_variant_consequence_ustop_gained:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Stop Gain"
    # --- 5' UTR Lost Events (Duller Yellow/Orange) ---
    five_prime_utr_variant_consequence_uaug_lost:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Start Lost"
    five_prime_utr_variant_consequence_ustop_lost:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Stop Lost"

  encode_custom:
    encode_eh_pr:
      color: "#FF8C00"
      label: "Not annotated in ENCODE\nannotated region"
    encode_tf:
      color: "#1D6498"
      label: "Variant in ENCODE\nannotated region"

  encode_regions:
    # --- Enhancer/Promoter regions ---
    encode_pls:
      color: "#E41A1C"  # Red (Standard for Active Promoters)
      label: "Promoter-Like Signature"
    encode_pels:
      color: "#FF8C00"
      label: "Proximal Enhancer-Like Signature"
    encode_dels:
      color: "#FFD700"
      label: "Distal Enhancer-Like Signature"
    # --- TF binding sites ---
    encode_tf:
      color: "#984EA3"  # Purple (For Transcription Factor Binding)
      label: "Transcription Factor Binding Only"
    encode_ca_tf:
      color: "#1D6498"
      label: "Accessible Region with TF Binding"

  vep_consequences:
    consequence_frameshift_variant:
      color: "#E31A1C"  # Dark Red
      label: "VEP Frameshift"
    consequence_stop_gained:
      color: "#FB9A99"  # Light Red
      label: "VEP Stop Gained"
    consequence_splice_donor_variant:
      color: "#6A1B9A"  # Deep Purple
      label: "VEP Splice Donor"
    consequence_splice_acceptor_variant:
      color: "#AB47BC"  # Lighter Orchid/Purple
      label: "VEP Splice Acceptor"
    # --- Start/Stop Lost Family (Oranges/Gold) ---
    consequence_start_lost:
      color: "#E65100"  # Dark Orange
      label: "VEP Start Lost"
    consequence_stop_lost:
      color: "#FFB300"  # Golden Yellow
      label: "VEP Stop Lost"
    consequence_missense_variant:
      color: "#1E90FF"  # Dodger Blue
      label: "VEP Missense"
    consequence_synonymous_variant:
      color: "#C6DBEF" # light blue
      label: "VEP Synonymous"
  # naive:
  #   relative_cds_position:
  #     color: "#b5de2b"
  #     label: "Relative CDS\nPosition"
  #     direction: -1