anngeno_file: /s/project/deeprvat/deeprvat_input/ukb_200k_wes_anngeno.ag
prs_pheno_map_file: /s/project/deeprvat/deeprvat_input/prs_pheno_map_clean.csv
prs_file: /s/project/deeprvat/deeprvat_input/PRS.parquet
association_testing_maf: 0.001

phenotypes_for_association_testing:
  - Apolipoprotein_A
  - Apolipoprotein_B
  - Calcium
  - Cholesterol_statin_corrected
  - Red_blood_cell_erythrocyte_count
  - HDL_cholesterol
  - IGF_1
  - LDL_direct_statin_corrected
  - Lymphocyte_percentage
  - Mean_platelet_thrombocyte_volume
  - Mean_corpuscular_volume
  - Mean_reticulocyte_volume
  - Neutrophill_count
  - Platelet_count
  - Platelet_crit
  - Platelet_distribution_width
  - SHBG
  - Standing_height
  - Total_bilirubin
  - Triglycerides
  - Urate

rare_variant_annotations:
  plof:
    - is_plof
    - loftee_hc
    - loftee_lc
    - Consequence_frameshift_variant
    - Consequence_start_lost
    - Consequence_start_lost_next_in_frame
    - Consequence_stop_gained
    - Consequence_stop_lost
    - CADD_PHRED
    - CADD_raw
  missense:
    - alphamissense
    - PrimateAI_score
    - sift_score
    - Consequence_missense_variant
    - Consequence_protein_altering_variant
  splicing:
    - Consequence_splice_acceptor_variant
    - Consequence_splice_donor_variant
    - Consequence_splice_region_variant
    - AbSplice_DNA
    - SpliceAI_delta_score
  regulatory:
    - influence_score_downstream
    - influence_score_upstream
    - GPN_MSA_score
    - abexp_min_with_testis_score
    - abexp_min_wo_testis_score
    - condel_score
    - polyphen_score
  misc:
    - MAFbeta
    - MAFmb
    - relative_cds_position
    - Consequence_inframe_deletion
    - Consequence_inframe_insertion
    

  # - GPN_MSA_score
  # - MAFbeta
  # - MAFmb
  # - AbSplice_DNA
  # - SpliceAI_delta_score
  # - abexp_min_with_testis_score
  # - abexp_min_wo_testis_score
  # - alphamissense
  # - condel_score
  # - influence_score_downstream
  # - influence_score_upstream
  # - is_plof
  # - loftee_hc
  # - loftee_lc
  # - polyphen_score
  # - relative_cds_position
  # - sift_score
  # - Consequence_frameshift_variant
  # - Consequence_inframe_deletion
  # - Consequence_inframe_insertion
  # - Consequence_missense_variant
  # - Consequence_protein_altering_variant
  # - Consequence_splice_acceptor_variant
  # - Consequence_splice_donor_variant
  # - Consequence_splice_region_variant
  # - Consequence_start_lost
  # - Consequence_start_lost_next_in_frame
  # - Consequence_stop_gained
  # - Consequence_stop_lost
  # - DeepRipe_plus_ELAVL1_parclip
  # - DeepRipe_plus_ELAVL1_parclip_is_nan
  # - DeepRipe_plus_HNRNPD_parclip
  # - DeepRipe_plus_HNRNPD_parclip_is_nan
  # - DeepRipe_plus_KHDRBS1_clip_k5
  # - DeepRipe_plus_KHDRBS1_clip_k5_is_nan
  # - DeepRipe_plus_MBNL1_parclip
  # - DeepRipe_plus_MBNL1_parclip_is_nan
  # - DeepRipe_plus_QKI_clip_k5
  # - DeepRipe_plus_QKI_clip_k5_is_nan
  # - DeepRipe_plus_QKI_lip_hg2
  # - DeepRipe_plus_QKI_lip_hg2_is_nan
  # - DeepRipe_plus_QKI_parclip
  # - DeepRipe_plus_QKI_parclip_is_nan
  # - DeepRipe_plus_TARDBP_parclip
  # - DeepRipe_plus_TARDBP_parclip_is_nan
  # - DeepSEA_PC_1
  # - DeepSEA_PC_1_is_nan
  # - DeepSEA_PC_2
  # - DeepSEA_PC_2_is_nan
  # - DeepSEA_PC_3
  # - DeepSEA_PC_3_is_nan
  # - DeepSEA_PC_4
  # - DeepSEA_PC_4_is_nan
  # - DeepSEA_PC_5
  # - DeepSEA_PC_5_is_nan
  # - DeepSEA_PC_6
  # - DeepSEA_PC_6_is_nan
  
covariates: #x_phenotypes
  - age
  - age2
  - age_sex
  - genetic_sex
  - genetic_PC_1
  - genetic_PC_2
  - genetic_PC_3
  - genetic_PC_4
  - genetic_PC_5
  - genetic_PC_6
  - genetic_PC_7
  - genetic_PC_8
  - genetic_PC_9
  - genetic_PC_10
  - genetic_PC_11
  - genetic_PC_12
  - genetic_PC_13
  - genetic_PC_14
  - genetic_PC_15
  - genetic_PC_16
  - genetic_PC_17
  - genetic_PC_18
  - genetic_PC_19
  - genetic_PC_20

# Additional settings if using the REGENIE integration
regenie_options:
  regenie_exp: True
  gtf_file: /s/project/deeprvat/deeprvat_input/gencode.v38.basic.annotation.gtf.gz
  pred_list: /s/project/deeprvat/ablations/regenie_input/deeprvat_pred_167k_bin_quant.list
  step_1:
      bgen: /s/project/deeprvat/deeprvat_input/imputed_genotypes_regenie/ukb_imputation_qc.bgen
      snplist: /s/project/deeprvat/deeprvat_input/imputed_genotypes_regenie/ukb_imputation_qc_plink.snplist
      bsize: 1000
      options:
          - "--sample /s/project/deeprvat/deeprvat_input/imputed_genotypes_regenie/ukb_imputation_qc_81358.sample_mapped"
          - "--qt"
  step_2:
      bsize: 400
      options:
          - "--qt"
      #TODO has to be adapted for disease traits

phenotype_prediction:
  cv_sample_file_dir: /s/project/deeprvat/deeprvat_input/sample_files/5_fold
  prs_pheno_map_file: /s/project/deeprvat/deeprvat_input/prs_pheno_map_clean.csv
  prs_file: /s/project/deeprvat/deeprvat_input/PRS.parquet
  min_n_genes: 5
  standardize_prs: True
  alpha: 0.05
  correction_type: "FDR"