site_name: UKBBGym Documentation
site_description: Benchmarking variant annotation scoring models against LOFTEE correlations in quantitative traits and Olink proteomics
repo_url: https://github.com/ShubhankarLondhe/ukbgym

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

nav:
  - Home: index.md
  - Data Processing: data_processing.md
  - Analysis Applets: analysis.md
  - Utilities: utils.md
  - Configuration Options: config.md
