maf: 0.001

covariates:
  - age
  - age2
  - age_sex
  - sex
  - genetic_pc_1
  - genetic_pc_2
  - genetic_pc_3
  - genetic_pc_4
  - genetic_pc_5
  - genetic_pc_6
  - genetic_pc_7
  - genetic_pc_8
  - genetic_pc_9
  - genetic_pc_10
  - genetic_pc_11
  - genetic_pc_12
  - genetic_pc_13
  - genetic_pc_14
  - genetic_pc_15
  - genetic_pc_16
  - genetic_pc_17
  - genetic_pc_18
  - genetic_pc_19
  - genetic_pc_20

biochemistry:
  - alanine_aminotransferase_int
  - albumin_int
  - alkaline_phosphatase_int
  - apolipoprotein_a_int
  - apolipoprotein_b_int
  - aspartate_aminotransferase_int
  - calcium_int
  - cholesterol_int
  - creactive_protein_int
  - creatinine_int
  - cystatin_c_int
  - direct_bilirubin_int
  - eosinophill_count_int
  - eosinophill_percentage_int
  - gamma_glutamyltransferase_int
  - glucose_int
  - glycated_haemoglobin_hba1c_int
  - haematocrit_percentage_int
  - haemoglobin_concentration_int
  - hdl_cholesterol_int
  - high_light_scatter_reticulocyte_count_int
  - high_light_scatter_reticulocyte_percentage_int
  - igf1_int
  - immature_reticulocyte_fraction_int
  - ldl_direct_int
  - lipoprotein_a_int
  - lymphocyte_count_int
  - lymphocyte_percentage_int
  - mean_corpuscular_haemoglobin_concentration_int
  - mean_corpuscular_haemoglobin_int
  - mean_corpuscular_volume_int
  - mean_platelet_thrombocyte_volume_int
  - mean_reticulocyte_volume_int
  - mean_sphered_cell_volume_int
  - microalbumin_in_urine_int
  - monocyte_count_int
  - monocyte_percentage_int
  - neutrophill_count_int
  - neutrophill_percentage_int
  - phosphate_int
  - platelet_count_int
  - platelet_crit_int
  - platelet_distribution_width_int
  - red_blood_cell_erythrocyte_count_int
  - red_blood_cell_erythrocyte_distribution_width_int
  - reticulocyte_count_int
  - reticulocyte_percentage_int
  - shbg_int
  - testosterone_int
  - total_bilirubin_int
  - total_protein_int
  - triglycerides_int
  - urate_int
  - urea_int
  - vitamin_d_int
  - white_blood_cell_leukocyte_count_int

fitness_phenotypes:
  # Physiological Reserve (Strength & Frailty)
  - hand_grip_strength_left_int
  - hand_grip_strength_right_int
  
  # Respiratory Function (Vitality & Aging)
  - forced_expiratory_volume_in_1second_fev1_best_measure_int
  - forced_vital_capacity_fvc_best_measure_int
  - peak_expiratory_flow_pef_int

  # Cardiovascular Health
  - pulse_rate_automated_reading_int
  - systolic_blood_pressure_automated_reading_int
  - diastolic_blood_pressure_automated_reading_int

  # Metabolic Health & Body Composition
  - basal_metabolic_rate_int
  - body_mass_index_bmi_int
  - waist_circumference_int
  - body_fat_percentage_int
  - whole_body_fatfree_mass_int
  - whole_body_water_mass_int

  # Cognitive Function (Processing & Intelligence)
  - fluid_intelligence_score_int
  - mean_time_to_correctly_identify_matches_int

  # Developmental Stability & Structure
  - birth_weight_int
  - standing_height_int

overall_phenotype:
  - arm_fat_mass_left_int
  - arm_fat_mass_right_int
  - arm_fat_percentage_left_int
  - arm_fat_percentage_right_int
  - arm_fatfree_mass_left_int
  - arm_fatfree_mass_right_int
  - arm_predicted_mass_left_int
  - arm_predicted_mass_right_int
  - basal_metabolic_rate_int
  - birth_weight_int
  - body_fat_percentage_int
  - body_mass_index_bmi_int
  - diastolic_blood_pressure_automated_reading_int
  - fluid_intelligence_score_int
  - forced_expiratory_volume_in_1second_fev1_best_measure_int
  - forced_expiratory_volume_in_1second_fev1_int
  - forced_expiratory_volume_in_1second_fev1_predicted_int
  - forced_expiratory_volume_in_1second_fev1_predicted_percentage_int
  - forced_vital_capacity_fvc_best_measure_int
  - forced_vital_capacity_fvc_int
  - hand_grip_strength_left_int
  - hand_grip_strength_right_int
  - hip_circumference_int
  - leg_fat_mass_left_int
  - leg_fat_mass_right_int
  - leg_fat_percentage_left_int
  - leg_fat_percentage_right_int
  - leg_fatfree_mass_left_int
  - leg_fatfree_mass_right_int
  - leg_predicted_mass_left_int
  - leg_predicted_mass_right_int
  - mean_time_to_correctly_identify_matches_int
  - peak_expiratory_flow_pef_int
  - pulse_rate_automated_reading_int
  - pulse_rate_int
  - sitting_height_int
  - standing_height_int
  - systolic_blood_pressure_automated_reading_int
  - trunk_fat_mass_int
  - trunk_fat_percentage_int
  - trunk_fatfree_mass_int
  - trunk_predicted_mass_int
  - waist_circumference_int
  - weight_int
  - whole_body_fat_mass_int
  - whole_body_fatfree_mass_int
  - whole_body_water_mass_int
  # - seated_height_int
  # - fathers_age_at_death_int
  # - mothers_age_at_death_int
  # - townsend_deprivation_index_at_recruitment_int
  # - heel_bone_mineral_density_bmd_left_int
  # - heel_bone_mineral_density_bmd_right_int
  # - heel_bone_mineral_density_bmd_tscore_automated_int
  # - heel_bone_mineral_density_bmd_tscore_automated_left_int
  # - heel_bone_mineral_density_bmd_tscore_automated_right_int


variant_consequences:
  intronic:
    - consequence_intron_variant
  missense:
    - consequence_missense_variant
  plof:
    - consequence_frameshift_variant
    - consequence_start_lost
    - consequence_stop_gained
    - consequence_stop_lost
    - consequence_splice_donor_variant
    - consequence_splice_acceptor_variant
  5utr_upstream10kb:
    - consequence_5_prime_utr_variant
    - consequence_upstream_gene_variant
  utr_annotator:
    - five_prime_utr_variant_consequence_uaug_gained
    - five_prime_utr_variant_consequence_uaug_lost
    - five_prime_utr_variant_consequence_uframeshift
    - five_prime_utr_variant_consequence_ustop_gained
    - five_prime_utr_variant_consequence_ustop_lost
  splicing:
    - consequence_splice_donor_variant
    - consequence_splice_acceptor_variant
    - consequence_splice_region_variant
    - consequence_splice_donor_5th_base_variant
    - consequence_splice_donor_region_variant
    - consequence_splice_polypyrimidine_tract_variant
  3utr_downstream10kb:
    - consequence_3_prime_utr_variant
    - consequence_downstream_gene_variant
  other_low_impact:
    - consequence_splice_donor_5th_base_variant
    - consequence_splice_donor_region_variant
    - consequence_splice_polypyrimidine_tract_variant
    - consequence_splice_region_variant
    - consequence_inframe_deletion
    - consequence_inframe_insertion
    - consequence_intergenic_variant
    - consequence_non_coding_transcript_exon_variant
    - consequence_non_coding_transcript_variant
    - consequence_protein_altering_variant
    - consequence_start_retained_variant
    - consequence_stop_retained_variant
    - consequence_synonymous_variant
    - consequence_coding_sequence_variant
  coding:
    - consequence_frameshift_variant
    - consequence_start_lost
    - consequence_stop_gained
    - consequence_stop_lost
    - consequence_splice_donor_variant
    - consequence_splice_acceptor_variant
    - consequence_missense_variant
    - consequence_protein_altering_variant
    - consequence_start_retained_variant
    - consequence_stop_retained_variant
    - consequence_synonymous_variant
    - consequence_coding_sequence_variant
    - consequence_inframe_deletion
    - consequence_inframe_insertion
  non_coding:
    - consequence_5_prime_utr_variant
    - consequence_upstream_gene_variant
    - consequence_splice_region_variant
    - consequence_splice_donor_5th_base_variant
    - consequence_splice_donor_region_variant
    - consequence_splice_polypyrimidine_tract_variant
    - consequence_intron_variant
    - consequence_3_prime_utr_variant
    # - consequence_downstream_gene_variant
  utrs:
    - consequence_5_prime_utr_variant
    - consequence_upstream_gene_variant
    - consequence_3_prime_utr_variant
    - consequence_downstream_gene_variant