correlation_categories:
  plof: "#fb9a99"
  missense: "#fdbf6f"
  splicing: "#b2df8a" #"#b3de69"
  conservation: "#cab2d6"
  regulatory: "#a6cee3"
# correlation_categories:
#   plof: "#fb8072"
#   missense: "#fdb462"
#   splicing: "#b3de69"
#   conservation: "#bc80bd"
#   regulatory: "#80b1d3"

rare_variant_annotations:
  plof:
    loftee_hc:
      color: "#E31A1C" # Dark Red
      label: "LOFTEE HC"

  missense:
    polyphen_score:
      color: "#feb72d"
      label: "PolyPhen2"
    sift_score:
      color: "#feb72d"
      label: "SIFT"
      direction: -1
    am_pathogenicity: 
      color: "#feb72d"
      label: "AlphaMissense"
    # esmscoremissense: 
    #   color: "#feb72d"
    #   label: "ESM1v"
    #   direction: -1
    esm1v:
      color: "#feb72d"
      label: "ESM1v"
      direction: -1
    cpt1_llr:
      color: "#feb72d"
      label: "CPT-1"
    revel_score:
      color: "#feb72d"
      label: "REVEL"
    clinpred_score:
      color: "#feb72d"
      label: "ClinPred"
    bayes_del:
      color: "#feb72d"
      label: "BayesDel"
    popeve:
      color: "#feb72d"
      label: "popEVE"
      direction: -1

  genetic_diversity:
    cadd_raw:
      color: "chocolate"
      label: "CADD Raw"

  gnomad:
    gnomade_af:
      color: "#00838F"  # Very Dark Green
      label: "gnomADe AF"
      direction: -1
    gnomadg_af:
      color: "#00838F"  # Very Dark Teal
      label: "gnomADg AF"
      direction: -1

  conservation:
    gpn_score: 
        color: "#942C80"  # Vibrant Magenta/Pink-Purple
        label: "GPN-MSA"
        direction: -1
    verphylop: 
      color: "#942C80"  # Darkest Blue
      label: "Vertebrate PhyloP"
    mamphylop: 
      color: "#942C80"  # Teal
      label: "Mammalian PhyloP"
    priphylop:
      color: "#942C80"  # Darkest Purple
      label: "Primate PhyloP"

  splicing:
    pangolin_score:
      color: "#28A745"
      label: "Pangolin"
    delta_score:
      color: "#28A745"
      label: "SpliceAI"
    absplice_dna_max:
      color: "#28A745"
      label: "AbSplice (max)"
    absplice2_max:
      color: "#28A745"
      label: "AbSplice2 (max)"
  
  regulatory:
    promoterai_abs: 
      color: "#1F77B4"
      label: "PromoterAI abs"
    promoterai_under:
      color: "#1F77B4"
      label: "PromoterAI"
      direction: -1
    abexp_min:
      color: "#1F77B4"
      label: "AbExp min"
      direction: -1
    fz_all_min:
      color: "#1F77B4"
      label: "Flashzoi min\nacross RNA (all)"
      direction: -1
    fz_gtex_min:
      color: "#1F77B4"
      label: "Flashzoi min\nacross RNA (GTEx)"
      direction: -1

  plof_consequences:
    consequence_frameshift_variant:
      color: "#E31A1C"  # Dark Red
      label: "VEP Frameshift"
    consequence_stop_gained:
      color: "#FB9A99"  # Light Red
      label: "VEP Stop Gained"
    consequence_splice_donor_variant:
      color: "#6A1B9A"  # Deep Purple
      label: "VEP Splice Donor"
    consequence_splice_acceptor_variant:
      color: "#AB47BC"  # Lighter Orchid/Purple
      label: "VEP Splice Acceptor"
    # --- Start/Stop Lost Family (Oranges/Gold) ---
    consequence_start_lost:
      color: "#E65100"  # Dark Orange
      label: "VEP Start Lost"
    consequence_stop_lost:
      color: "#FFB300"  # Golden Yellow
      label: "VEP Stop Lost"
    # loftee_lc:
    #   color: "#C6DBEF" # light blue
    #   label: "LOFTEE LC"
    # loftee_hc:
    #   color: "#1E90FF"  # Dodger Blue
    #   label: "LOFTEE HC"
  
  clinvar:
    clinvar_patho:
      color: "#1E90FF"  # Dodger Blue
      label: "ClinVar Pathogenic"
    clinvar_likely_patho:
      color: "#1E90FF"  # Dodger Blue
      label: "ClinVar Likely Pathogenic"
    clinvar_benign:
      color: "#1E90FF"  # Dodger Blue
      label: "ClinVar Benign"
    clinvar_likely_benign:
      color: "#1E90FF"  # Dodger Blue
      label: "ClinVar Likely Benign"

  dubious_plof:
    start_stop_lost:
      color: "#C6DBEF" # light blue
      label: "Start/Stop Lost"

  protein_domains:
    ted_domain:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    non_ted_domain:
      color: "#2E8B57"  # Sea Green
      label: "Non Structured Domain"
    # mobi_curated_disorder_priority:
    #   color: "#E31A1C"  # Dark Red
    #   label: "Disordered Domain"
    mobi_full_disorder_priority:
      color: "#E31A1C"  # Dark Red
      label: "Disordered Domain"
    mobi_full_lip_priority:
      color: "#1E90FF"  # Dodger Blue
      label: "Linear Interacting Peptides"
    low_complexity_domain:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low Complexity Domain"
  
  loftee_protein_domains:
    loftee_disorder:
      color: "#E31A1C"  # Dark Red
      label: "Disordered Domain"
    loftee_lip:
      color: "#1E90FF"  # Dodger Blue
      label: "Linear Interacting Peptides"
    loftee_ted:
      color: "#2E8B57"  # Sea Green
      label: "Structured Domain"
    loftee_low_complexity:
      color: "#FF9933"  # Amber/Dark Orange
      label: "Low Complexity Domain"

  5utr:
    five_prime_utr_variant_consequence_uaug_gained:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Start Gain"
    five_prime_utr_variant_consequence_ustop_gained:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Stop Gain"
    # --- 5' UTR Lost Events (Duller Yellow/Orange) ---
    five_prime_utr_variant_consequence_uaug_lost:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Start Lost"
    five_prime_utr_variant_consequence_ustop_lost:
      color: "#DAA520"  # Goldenrod
      label: "5' UTR Stop Lost"

  3utr:
    aparent2:
      color: "#FFA500"  # Orange (uSTOP Gained)
      label: "Aparent 2"

  encode_custom:
    encode_eh_pr:
      color: "#FF8C00"
      label: "Not annotated in ENCODE\nannotated region"
    encode_tf:
      color: "#1D6498"
      label: "Variant in ENCODE\nannotated region"

  encode_regions:
    # --- Enhancer/Promoter regions ---
    encode_pls:
      color: "#E41A1C"  # Red (Standard for Active Promoters)
      label: "Promoter-Like Signature"
    encode_pels:
      color: "#FF8C00"
      label: "Proximal Enhancer-Like Signature"
    encode_dels:
      color: "#FFD700"
      label: "Distal Enhancer-Like Signature"
    # --- TF binding sites ---
    encode_tf:
      color: "#984EA3"  # Purple (For Transcription Factor Binding)
      label: "Transcription Factor Binding Only"
    encode_ca_tf:
      color: "#1D6498"
      label: "Accessible Region with TF Binding"
  
  indel_lengths:
    1bp_del:
      color: "#C6DBEF"
      label: "1bp deletion"
    1bp_ins:
      color: "#C6DBEF"
      label: "1bp insertion"
    2_5bp_del:
      color: "#C6DBEF"
      label: "2-5bp deletion"
    2_5bp_ins:
      color: "#C6DBEF"
      label: "2-5bp insertion"
    gt_5bp_del:
      color: "#C6DBEF"
      label: ">5bp deletion"
    gt_5bp_ins:
      color: "#C6DBEF"
      label: ">5bp insertion"

  coding_indels:
    inframe_deletion:
      color: "#C6DBEF"
      label: "inframe deletion"
    inframe_insertion:
      color: "#C6DBEF"
      label: "inframe insertion"
    consequence_synonymous_variant:
      color: "#C6DBEF"
      label: "synonymous"
    consequence_missense_variant:
      color: "#C6DBEF"
      label: "missense"
    loftee_hc:
      color: "#E31A1C"  # Dodger Blue
      label: "LOFTEE HC"
    
  non_coding_regions:
    core_promoter:
      color: "#00A99D"
      label: "Core promoter (TSS±50bp)"
    proximal_promoter:
      color: "#00A99D"
      label: "Proximal promoter (TSS±500bp)"
    encode_promoter:
      color: "#FF8C00"
      label: "Promoter region (ENCODE)"
    encode_enhancer:
      color: "#1D6498"
      label: "Enhancer region (ENCODE)"
    encode_any_tf:
      color: "#41AB5D"  # Medium Green
      label: "TF binding region (ENCODE)"

  # vep_consequences:
  #   consequence_frameshift_variant:
  #     color: "#E31A1C"  # Dark Red
  #     label: "VEP Frameshift"
  #   consequence_stop_gained:
  #     color: "#FB9A99"  # Light Red
  #     label: "VEP Stop Gained"
  #   consequence_splice_donor_variant:
  #     color: "#6A1B9A"  # Deep Purple
  #     label: "VEP Splice Donor"
  #   consequence_splice_acceptor_variant:
  #     color: "#AB47BC"  # Lighter Orchid/Purple
  #     label: "VEP Splice Acceptor"
  #   # --- Start/Stop Lost Family (Oranges/Gold) ---
  #   consequence_start_lost:
  #     color: "#E65100"  # Dark Orange
  #     label: "VEP Start Lost"
  #   consequence_stop_lost:
  #     color: "#FFB300"  # Golden Yellow
  #     label: "VEP Stop Lost"
  #   consequence_missense_variant:
  #     color: "#1E90FF"  # Dodger Blue
  #     label: "VEP Missense"
  #   consequence_synonymous_variant:
  #     color: "#C6DBEF" # light blue
  #     label: "VEP Synonymous"